name: Azure Service Creation Workflow for ASPNETMVC Lab

on:
  push:
    branches:
    - Hackathon
    paths:
    - SERVICECREATE.md

env:
  AZURE_RESOURCE_GROUP: devops-test              # set this to your Azure Resource group's name
  AZURE_STORAGE_ACCOUNT: joshistorageaccount      # set this to your Azure Storage account name for images
  AZURE_LOCATION: eastus                          # set this to your azure resource group location   
  AZURE_APP_PLAN: devopscoreplan                    # set netcoreplan  
  AZURE_APIAPP_NAME: devopsapiapp                 # set this to your API Website name
  AZURE_WEBAPP_NAME: devopsfrontweb               # set this to your frontend website name


jobs:
  CREATEAZURESERVICES:
    runs-on: ubuntu-latest


    steps:

      - uses: actions/checkout@master  # Checkout the repo to Hosted Runner 
      - uses: azure/login@v1  	       # Authenticate to Azure
        with:
          creds: ${{ secrets.DEPLOYGITHUB }}  
      - name: Azure CLI script to create azure services on subscription
        uses: azure/CLI@v1
        with:
         azcliversion: latest
         inlineScript: |
          az group create --name ${{ env.AZURE_RESOURCE_GROUP }} --location ${{ env.AZURE_LOCATION }} 
          az appservice plan create --resource-group ${{ env.AZURE_RESOURCE_GROUP }} --name ${{ env.AZURE_APP_PLAN }} --is-linux --sku S1
          az webapp create --resource-group ${{ env.AZURE_RESOURCE_GROUP }} --plan ${{ env.AZURE_APP_PLAN }} --name ${{ env.AZURE_APIAPP_NAME }}  --runtime "DOTNETCORE|3.1"
          az webapp create --resource-group ${{ env.AZURE_RESOURCE_GROUP }} --plan ${{ env.AZURE_APP_PLAN }} --name ${{ env.AZURE_WEBAPP_NAME }}  --runtime "DOTNETCORE|3.1"
          
